language: rust

branches:
  only:
    - master

jobs:
  include:
    # Run on cron to generate a PR
    - stage: bump nightly
      if: type = cron

      before_script:
        - git config --global user.name "Travis-CI"
        - git config credential.helper "store --file=.git/credentials"
        - echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials

      script:
        - ./bin/nightly-pr.sh

    # Default tests
    - stage: test
      if: type != cron

      cache: cargo

      before_cache:
        - rm -rf "$TRAVIS_HOME/.cargo/registry/src"
        - cargo sweep --file

      addons:
        apt:
          packages:
            - jq
            - libssl-dev

      before_install:
        - rustup component add clippy
        - rustup component add rustfmt
        # Make sure local dev environment will work as well for nightly toolchains
        - rustup component add rls
        - rustup component add rust-analysis
        - rustup component add rust-src
        # Cargo tools
        - cargo audit --version | grep $(curl 'https://crates.io/api/v1/crates/cargo-audit' | jq '.crate.max_version' | tr -d '"') || cargo install cargo-audit --force
        - cargo sweep --version | grep $(curl 'https://crates.io/api/v1/crates/cargo-sweep' | jq '.crate.max_version' | tr -d '"') || cargo install cargo-sweep --force
        # https://github.com/xd009642/tarpaulin/issues/150
        - cargo tarpaulin --version | grep $(curl 'https://crates.io/api/v1/crates/cargo-tarpaulin' | jq '.crate.max_version' | tr -d '"') || cargo install cargo-tarpaulin --force

      before_script:
        - cargo sweep --stamp

      script:
        - cargo audit
        - cargo fmt --all -- --check
        - cargo build
        - cargo clippy --all-targets --all-features -- -D warnings
        - cargo test --all

      after_success: |
        cargo tarpaulin --out Xml
        bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: always
