language: rust
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
branches:
  only:
    - master
cache: cargo
addons:
  apt:
    packages:
      - libssl-dev
      - jq
before_install:
  - rustup component add clippy
install: |
  # https://github.com/xd009642/tarpaulin/issues/150
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    cargo tarpaulin --version | grep $(curl 'https://crates.io/api/v1/crates/cargo-tarpaulin' | jq '.crate.max_version' | tr -d '"') || RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
  fi
script:
  - cargo build
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    #cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID

    # Uncomment the following two lines create and upload a report for codecov.io
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
notifications:
  email:
    on_success: always
