language: rust
dist: bionic

# Global settings
branches:
  only:
    - master

stages:
  - name: bump nightly
    if: type = cron
  - name: test
    if: type != cron

cache: cargo

before_cache:
  - rm -rf "$TRAVIS_HOME/.cargo/registry/src"
  - rm -rf target
  - ./bin/nightly-cleanup.sh

notifications:
  email:
    on_success: always

jobs:
  include:
    # Run on cron to generate a PR
    - stage: bump nightly
      cache: false
      before_script:
        - git config --global user.name "Travis-CI"
        - git config credential.helper "store --file=.git/credentials"
        - echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials
      script:
        - ./bin/nightly-pr.sh

    - stage: test
      addons:
        apt:
          packages:
            - jq
      services:
        - postgresql
        - redis-server
      before_install:
        - curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -
        - rustup component add clippy
        - rustup component add rustfmt
        # Make sure local dev environment will work as well for nightly toolchains
        - rustup component add rls
        - rustup component add rust-analysis
        - rustup component add rust-src
        # Intall cargo tools if not installed
        # - cargo audit --version | grep $(curl 'https://crates.io/api/v1/crates/cargo-audit' | jq '.crate.max_version' | tr -d '"') || cargo install cargo-audit --force
        - diesel --version | grep $(curl 'https://crates.io/api/v1/crates/diesel_cli' | jq '.crate.max_version' | tr -d '"') || cargo install diesel_cli --no-default-features --features=postgres --force
      before_script:
        # Setup database
        - psql -c 'create database travis_ci_test;' -U postgres
        - echo "DATABASE_URL=postgres://postgres@localhost/travis_ci_test" >> .env
        - echo "REDIS_URL=redis://localhost" >> .env
        - diesel database setup --database-url=postgres://postgres@localhost/travis_ci_test
      script:
        - export CARGO_INCREMENTAL=0
        - export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads"
        # - cargo audit
        - cargo fmt --all -- --check
        - cargo build --verbose
        - cargo clippy --all-targets --all-features -- -D warnings
        - cargo test --verbose
        - |
          zip -0 ccov.zip `find . \( -name "d20*.gc*" \) -print`;
          ./grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore-dir "/*" -o lcov.info;
          bash <(curl -s https://codecov.io/bash) -f lcov.info;
