language: rust

branches:
  only:
    - master

jobs:
  include:
    # Run on cron to generate a PR
    - stage: bump nightly
      if: type = cron

      before_script:
        - git config --global user.name "Travis-CI"
        - git config credential.helper "store --file=.git/credentials"
        - echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials

      script:
        - ./bin/nightly-pr.sh

    # Default tests
    - stage: test
      if: type != cron

      cache:
        directories:
          - $HOME/.cargo

      # https://levans.fr/rust_travis_cache.html
      before_cache:
        - rm -rf $HOME/.cargo/registry

      addons:
        apt:
          packages:
            - jq
            - libssl-dev

      before_install:
        - rustup component add clippy
        - rustup component add rustfmt
        # https://github.com/xd009642/tarpaulin/issues/150
        - cargo tarpaulin --version | grep $(curl 'https://crates.io/api/v1/crates/cargo-tarpaulin' | jq '.crate.max_version' | tr -d '"') || RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin --force

      script:
        - cargo build
        - cargo fmt -- --check
        - cargo clippy --all-targets --all-features -- -D warnings
        - cargo test

      after_success: |
        cargo tarpaulin --out Xml
        bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: always
