[package]
name = "d20"
version = "0.1.0"
authors = ["Ben Brandt <benjamin.j.brandt@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "*"
env_logger = "*"
log = "*"
rand = "*"
sentry = "*"
sentry-actix = "*"
serde = { version = "*", features = ["derive"] }
serde_derive = "*"
serde_json = "*"
