[package]
name = "d20"
version = "0.1.0"
authors = ["Ben Brandt <benjamin.j.brandt@gmail.com>"]
edition = "2018"

[dependencies]
env_logger = "0.6"
futures-preview = "0.3.0-alpha.16"
http-service = "0.2"
juniper = "0.12"
log = "0.4"
mime = "0.3"
rand = "0.7"
regex = "1"
sentry = "0.15"
serde = { version = "1", features = ["derive"] }
serde_derive = "1"
serde_json = "1"
tide = "0.2"
