[package]
name = "d20"
version = "0.1.0"
authors = ["Ben Brandt <benjamin.j.brandt@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
diesel = { version = "1", features = ["postgres", "extras"] }
dotenv = "0.14"
env_logger = "0.6"
failure = "0.1"
http-service = "0.3"
jsonwebtoken = "6"
juniper = "0.13"
log = "0.4"
mime = "0.3"
r2d2_redis = "0.10"
rand = "0.7"
rand_pcg = "0.2"
regex = "1"
sentry = "0.15"
serde = { version = "1", features = ["derive"] }
serde_derive = "1"
serde_json = "1"
tide = { git = "https://github.com/rustasync/tide" }
tide-compression = { git = "https://github.com/rustasync/tide" }
